# Generated by Django 2.2.4 on 2019-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=10)),
                ('lugar', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=10)),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('presencial', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombres', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=10)),
            ],
        ),
    ]
