# Generated by Django 2.2.4 on 2019-08-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('conferencia', 'Conferencia'), ('seminario', 'Seminario'), ('congreso', 'Congreso'), ('curso', 'Curso')], default='conferencia', max_length=10),
        ),
    ]
